Watching for file changes with StatReloader
Bad Request: /api/v1/account/register/
"POST /api/v1/account/register/ HTTP/1.1" 400 105
Bad Request: /api/v1/account/register/
"POST /api/v1/account/register/ HTTP/1.1" 400 105
Bad Request: /api/v1/dj-rest-auth/password/reset/confirm/
"POST /api/v1/dj-rest-auth/password/reset/confirm/ HTTP/1.1" 400 35
Bad Request: /api/v1/dj-rest-auth/password/reset/confirm/
"POST /api/v1/dj-rest-auth/password/reset/confirm/ HTTP/1.1" 400 27
Watching for file changes with StatReloader
Unauthorized: /api/v1/dj-rest-auth/password/reset/
"POST /api/v1/dj-rest-auth/password/reset/ HTTP/1.1" 401 183
"POST /api/v1/account/api/token/ HTTP/1.1" 200 483
"POST /api/v1/dj-rest-auth/password/reset/ HTTP/1.1" 200 49
Internal Server Error: /api/v1/dj-rest-auth/password/reset/
Traceback (most recent call last):
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/dj_rest_auth/views.py", line 255, in post
    serializer.save()
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/dj_rest_auth/serializers.py", line 260, in save
    self.reset_form.save(**opts)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/dj_rest_auth/forms.py", line 42, in save
    path = reverse(
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_confirm' not found. 'password_reset_confirm' is not a valid view function or pattern name.
"POST /api/v1/dj-rest-auth/password/reset/ HTTP/1.1" 500 112383
Internal Server Error: /api/v1/dj-rest-auth/password/reset/
Traceback (most recent call last):
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/dj_rest_auth/views.py", line 255, in post
    serializer.save()
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/dj_rest_auth/serializers.py", line 260, in save
    self.reset_form.save(**opts)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/dj_rest_auth/forms.py", line 42, in save
    path = reverse(
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_confirm' not found. 'password_reset_confirm' is not a valid view function or pattern name.
"POST /api/v1/dj-rest-auth/password/reset/ HTTP/1.1" 500 112383
Internal Server Error: /api/v1/dj-rest-auth/password/reset/
Traceback (most recent call last):
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/dj_rest_auth/views.py", line 255, in post
    serializer.save()
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/dj_rest_auth/serializers.py", line 260, in save
    self.reset_form.save(**opts)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/dj_rest_auth/forms.py", line 42, in save
    path = reverse(
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_confirm' not found. 'password_reset_confirm' is not a valid view function or pattern name.
"POST /api/v1/dj-rest-auth/password/reset/ HTTP/1.1" 500 112383
Internal Server Error: /api/v1/dj-rest-auth/password/reset/
Traceback (most recent call last):
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/dj_rest_auth/views.py", line 255, in post
    serializer.save()
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/dj_rest_auth/serializers.py", line 260, in save
    self.reset_form.save(**opts)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/dj_rest_auth/forms.py", line 42, in save
    path = reverse(
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_confirm' not found. 'password_reset_confirm' is not a valid view function or pattern name.
"POST /api/v1/dj-rest-auth/password/reset/ HTTP/1.1" 500 112383
/Users/kachigos/Desktop/green_star/config/urls.py changed, reloading.
Watching for file changes with StatReloader
"POST /api/v1/dj-rest-auth/password/reset/ HTTP/1.1" 200 49
"POST /api/v1/dj-rest-auth/password/reset/ HTTP/1.1" 200 49
"POST /api/v1/dj-rest-auth/password/reset/ HTTP/1.1" 200 49
/Users/kachigos/Desktop/green_star/config/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/kachigos/Desktop/green_star/config/settings.py changed, reloading.
Watching for file changes with StatReloader
Unauthorized: /api/v1/dj-rest-auth/password/reset/
"POST /api/v1/dj-rest-auth/password/reset/ HTTP/1.1" 401 183
"POST /api/v1/account/api/token/ HTTP/1.1" 200 483
Unauthorized: /api/v1/dj-rest-auth/password/reset/
"POST /api/v1/dj-rest-auth/password/reset/ HTTP/1.1" 401 107
Watching for file changes with StatReloader
Internal Server Error: /api/v1/dj-rest-auth/password/reset/
Traceback (most recent call last):
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/dj_rest_auth/views.py", line 255, in post
    serializer.save()
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/dj_rest_auth/serializers.py", line 260, in save
    self.reset_form.save(**opts)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/dj_rest_auth/forms.py", line 60, in save
    get_adapter(request).send_mail(
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/allauth/account/adapter.py", line 140, in send_mail
    msg.send()
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 69, in open
    self.connection.login(self.username, self.password)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 750, in login
    raise last_exception
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials bi37-20020a05651c232500b00261e7e7b698sm114386ljb.123 - gsmtp')
"POST /api/v1/dj-rest-auth/password/reset/ HTTP/1.1" 500 136651
Watching for file changes with StatReloader
Internal Server Error: /api/v1/dj-rest-auth/password/reset/
Traceback (most recent call last):
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/dj_rest_auth/views.py", line 255, in post
    serializer.save()
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/dj_rest_auth/serializers.py", line 260, in save
    self.reset_form.save(**opts)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/dj_rest_auth/forms.py", line 60, in save
    get_adapter(request).send_mail(
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/allauth/account/adapter.py", line 140, in send_mail
    msg.send()
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 69, in open
    self.connection.login(self.username, self.password)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 750, in login
    raise last_exception
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.9 Application-specific password required. Learn more at\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor k13-20020ac257cd000000b0049461916b95sm1807559lfo.20 - gsmtp')
"POST /api/v1/dj-rest-auth/password/reset/ HTTP/1.1" 500 136731
Watching for file changes with StatReloader
"POST /api/v1/account/api/token/ HTTP/1.1" 200 483
"POST /api/v1/dj-rest-auth/password/reset/ HTTP/1.1" 200 49
Method Not Allowed: /rest-auth/password/reset/confirm/7/bb2ola-9976f278b7880655cc1f8aecafdcb803
"GET /rest-auth/password/reset/confirm/7/bb2ola-9976f278b7880655cc1f8aecafdcb803 HTTP/1.1" 405 8786
"GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
"GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
"GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
"GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
"GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
"GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
"GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
"GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
"GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
Bad Request: /api/v1/dj-rest-auth/password/reset/confirm/
"POST /api/v1/dj-rest-auth/password/reset/confirm/ HTTP/1.1" 400 25
Bad Request: /api/v1/dj-rest-auth/password/reset/confirm/
"POST /api/v1/dj-rest-auth/password/reset/confirm/ HTTP/1.1" 400 27
Bad Request: /api/v1/dj-rest-auth/password/reset/confirm/
"POST /api/v1/dj-rest-auth/password/reset/confirm/ HTTP/1.1" 400 27
"POST /api/v1/dj-rest-auth/password/reset/ HTTP/1.1" 200 49
Method Not Allowed: /rest-auth/password/reset/confirm/7/bb2pd1-90f56106563760eede88b93eb3051bd4
"GET /rest-auth/password/reset/confirm/7/bb2pd1-90f56106563760eede88b93eb3051bd4 HTTP/1.1" 405 8786
"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
"GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
"GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
"GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
"GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
"GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
"GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
"GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
"GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
"GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
Internal Server Error: /rest-auth/password/reset/confirm/7/bb2pd1-90f56106563760eede88b93eb3051bd4
Traceback (most recent call last):
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_auth/views.py", line 209, in dispatch
    return super(PasswordResetConfirmView, self).dispatch(*args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_auth/views.py", line 213, in post
    serializer.is_valid(raise_exception=True)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "/Users/kachigos/Desktop/green_star/venv/lib/python3.10/site-packages/rest_auth/serializers.py", line 208, in validate
    uid = force_text(uid_decoder(attrs['uid']))
NameError: name 'force_text' is not defined
"POST /rest-auth/password/reset/confirm/7/bb2pd1-90f56106563760eede88b93eb3051bd4 HTTP/1.1" 500 123008
Bad Request: /api/v1/dj-rest-auth/password/reset/confirm/
"POST /api/v1/dj-rest-auth/password/reset/confirm/ HTTP/1.1" 400 156
"POST /api/v1/dj-rest-auth/password/reset/confirm/ HTTP/1.1" 200 59
Watching for file changes with StatReloader
Not Found: /api/v1/dj-rest-auth/ login/ 
"POST /api/v1/dj-rest-auth/%20login/%20 HTTP/1.1" 404 4940
Not Found: /api/v1/dj-rest-auth/ login/ 
"POST /api/v1/dj-rest-auth/%20login/%20 HTTP/1.1" 404 4940
Not Found: /api/v1/dj-rest-auth/ login/ 
"POST /api/v1/dj-rest-auth/%20login/%20 HTTP/1.1" 404 4940
"GET /admin/ HTTP/1.1" 200 13112
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/css/login.css HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
"GET /static/admin/css/fonts.css HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/css/fonts.css HTTP/1.1" 304 0
"GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
"GET /admin/authtoken/tokenproxy/ HTTP/1.1" 200 11180
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/js/core.js HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
"GET /static/admin/css/changelists.css HTTP/1.1" 304 0
"GET /static/admin/js/actions.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
"GET /static/admin/js/urlify.js HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/css/fonts.css HTTP/1.1" 304 0
"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
"GET /admin/auth/user/ HTTP/1.1" 200 16630
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/css/changelists.css HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
"GET /static/admin/js/core.js HTTP/1.1" 304 0
"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
"GET /static/admin/js/actions.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
"GET /static/admin/js/urlify.js HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/css/fonts.css HTTP/1.1" 304 0
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
"GET /static/admin/img/search.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 3325
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
"GET /admin/auth/user/6/change/ HTTP/1.1" 200 25081
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
"GET /static/admin/css/forms.css HTTP/1.1" 304 0
"GET /static/admin/js/core.js HTTP/1.1" 304 0
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/js/SelectBox.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/js/calendar.js HTTP/1.1" 304 0
"GET /static/admin/js/SelectFilter2.js HTTP/1.1" 304 0
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/js/actions.js HTTP/1.1" 304 0
"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
"GET /static/admin/js/urlify.js HTTP/1.1" 304 0
"GET /static/admin/css/widgets.css HTTP/1.1" 304 0
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
"GET /static/admin/css/fonts.css HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/js/change_form.js HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 3325
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
"GET /static/admin/img/selector-icons.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-unknown.svg HTTP/1.1" 304 0
"GET /static/admin/img/search.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 304 0
Not Found: / admin
"GET /%20admin HTTP/1.1" 404 3759
"GET /admin/ HTTP/1.1" 200 13112
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/css/fonts.css HTTP/1.1" 304 0
"GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 200 13112
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
"GET /static/admin/css/fonts.css HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
Not Found: /api/v1/dj-rest-auth/
"GET /api/v1/dj-rest-auth/ HTTP/1.1" 404 4911
"GET /api/v1/api-auth/login/ HTTP/1.1" 200 2707
"GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
"GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
"GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
Not Found: /api/v1/api-auth/
"GET /api/v1/api-auth/ HTTP/1.1" 404 4039
"GET /api/v1/api-auth/login/ HTTP/1.1" 200 2707
"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
"GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
"GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
"GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
"POST /api/v1/api-auth/login/ HTTP/1.1" 200 2944
"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
"GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
"GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
"GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
"POST /api/v1/api-auth/login/ HTTP/1.1" 302 0
Not Found: /accounts/profile/
"GET /accounts/profile/ HTTP/1.1" 404 3790
Forbidden (CSRF token missing or incorrect.): /api/v1/api-auth/login/
"POST /api/v1/api-auth/login/ HTTP/1.1" 403 2519
Forbidden (CSRF token missing or incorrect.): /api/v1/api-auth/login/
"POST /api/v1/api-auth/login/ HTTP/1.1" 403 2519
"GET /api/v1/api-auth/login/ HTTP/1.1" 200 2707
Forbidden (CSRF token missing or incorrect.): /api/v1/api-auth/login/
"POST /api/v1/api-auth/login/ HTTP/1.1" 403 2519
Forbidden (CSRF token missing or incorrect.): /api/v1/api-auth/login/
"POST /api/v1/api-auth/login/ HTTP/1.1" 403 2519
